import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

import { kvGet, kvSet } from '../lib/kv';

export type AppLanguage = 'zh' | 'en';

const LANGUAGE_KEY = 'smartpet.app-language';

const messages = {
  zh: {
    devices: '设备',
    bind: '绑定',
    records: '记录',
    messages: '消息',
    me: '我的',
    meSubtitle: '账号、隐私与帮助',
    normal: '正常',
    suspended: '已停用',
    inactive: '未激活',
    language: '语言',
    languageDescription: '选择 App 显示语言',
    chinese: '中文',
    english: 'English',
    petsAndDevices: '宠物与设备',
    petProfiles: '宠物档案',
    localStorage: '本地存储',
    storageAndCache: '存储与缓存',
    privacyConsent: '隐私与数据采集授权',
    dataConsent: '数据采集授权',
    consentLoading: '正在读取当前账号的授权状态…',
    consentEnabled: '已授权：App 可采集并上传设备声音、行为与状态数据。',
    consentDisabled: '已关闭：将停止后台采集与数据同步。',
    saving: '正在保存…',
    helpAndFeedback: '帮助与反馈',
    faq: '常见问题与反馈',
    signOut: '退出登录',
    signOutMessage: '退出后需重新登录才能访问设备与数据。确定退出吗？',
    helpMessage: '如遇问题，请先在设备详情页检查连接状态。更多帮助与反馈渠道将在后续版本提供。',
    understood: '知道了',
    close: '关闭',
    openItem: (label: string) => `打开${label}`,
    login: '登录',
    register: '注册',
    email: '邮箱',
    password: '密码',
    setPassword: '设置密码',
    setPasswordHint: '设置密码（至少 8 位）',
    confirmPassword: '确认密码',
    registerAndLogin: '注册并登录',
    retryLogin: '重新登录',
    loggingIn: '正在登录…',
    registering: '正在注册…',
    retryHint: '网络恢复后可直接点击下方按钮重试',
    loginConsent: '我已阅读并同意《用户协议》《隐私政策》，并授权 SmartPet 采集和上传设备产生的声音、行为和设备状态数据。',
    captcha: '图形验证码',
    refreshCaptcha: '点击刷新验证码',
    captchaLoadFailed: '加载失败\n点击重试',
    captchaGet: '点击获取',
    restoringSession: '正在恢复登录状态…',
    connectionUnavailable: '暂时无法连接',
    recoveryHint: '不会退出账号或清除登录信息，请在网络恢复后重试。',
    reconnect: '重新连接',
    invalidEmail: '请输入有效的邮箱地址',
    enterPassword: '请输入密码',
    acceptConsent: '请先阅读并同意页面底部的协议与数据采集授权',
    accountNotRegistered: '该邮箱尚未注册，请设置密码并输入验证码完成注册',
    passwordMin: '密码至少 8 位',
    passwordMismatch: '两次输入的密码不一致',
    enterCaptcha: '请输入图形验证码',
    emailRegistered: '该邮箱已注册，请直接登录',
    loginProfileTimeout: '密码验证已通过，但加载账号信息超时，请重新登录',
    loginProfileNetwork: '密码验证已通过，但当前网络不可用，请检查网络后重试',
    loginProfileServer: '密码验证已通过，但服务器暂时无法加载账号信息，请重试',
    loginSessionFailed: '密码验证已通过，但登录状态建立失败，请重试',
    connectionTimeout: '连接服务器超时，请稍后重试',
    networkFailed: '网络连接失败，请检查网络后重试',
    credentialsInvalid: '邮箱或密码错误，请重试',
    accountSuspended: '账号已被停用，请联系客服',
    credentialsFormatInvalid: '邮箱或密码格式不正确',
    tooManyAttempts: '尝试次数过多，请稍后再试',
    serverUnavailable: '服务器暂时不可用，请稍后重试',
    requestFailed: '请求失败，请稍后再试',
    unknownError: '发生未知错误，请稍后重试',
    captchaInvalid: '验证码错误或已过期，请重新输入',
    registrationFormatInvalid: '邮箱、密码或验证码格式不正确',
    registrationFailed: '注册失败，请稍后再试',
  },
  en: {
    devices: 'Devices',
    bind: 'Bind',
    records: 'Records',
    messages: 'Messages',
    me: 'Me',
    meSubtitle: 'Account, privacy and support',
    normal: 'Active',
    suspended: 'Suspended',
    inactive: 'Inactive',
    language: 'Language',
    languageDescription: 'Choose the app display language',
    chinese: '中文',
    english: 'English',
    petsAndDevices: 'Pets & devices',
    petProfiles: 'Pet profiles',
    localStorage: 'Local storage',
    storageAndCache: 'Storage & cache',
    privacyConsent: 'Privacy & data collection',
    dataConsent: 'Data collection consent',
    consentLoading: 'Reading consent status for this account…',
    consentEnabled: 'Enabled: the app may collect and upload device audio, behavior and status data.',
    consentDisabled: 'Disabled: background collection and data sync are stopped.',
    saving: 'Saving…',
    helpAndFeedback: 'Help & feedback',
    faq: 'FAQ & feedback',
    signOut: 'Sign out',
    signOutMessage: 'You will need to sign in again to access devices and data. Sign out now?',
    helpMessage: 'If you encounter a problem, first check the connection status on the device details screen. More support channels will be available in a future version.',
    understood: 'Got it',
    close: 'Close',
    openItem: (label: string) => `Open ${label}`,
    login: 'Log in',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    setPassword: 'Set password',
    setPasswordHint: 'Set password (at least 8 characters)',
    confirmPassword: 'Confirm password',
    registerAndLogin: 'Register & log in',
    retryLogin: 'Try logging in again',
    loggingIn: 'Logging in…',
    registering: 'Registering…',
    retryHint: 'When the network recovers, tap the button below to retry.',
    loginConsent: 'I have read and agree to the User Agreement and Privacy Policy, and authorize SmartPet to collect and upload audio, behavior and device status data generated by the device.',
    captcha: 'Security code',
    refreshCaptcha: 'Tap to refresh the security code',
    captchaLoadFailed: 'Load failed\nTap to retry',
    captchaGet: 'Tap to load',
    restoringSession: 'Restoring your session…',
    connectionUnavailable: 'Unable to connect',
    recoveryHint: 'Your account and sign-in information will be kept. Try again when the network recovers.',
    reconnect: 'Reconnect',
    invalidEmail: 'Enter a valid email address.',
    enterPassword: 'Enter your password.',
    acceptConsent: 'Read and accept the agreements and data collection consent below first.',
    accountNotRegistered: 'This email is not registered. Set a password and enter the security code to register.',
    passwordMin: 'Password must be at least 8 characters.',
    passwordMismatch: 'The passwords do not match.',
    enterCaptcha: 'Enter the security code.',
    emailRegistered: 'This email is already registered. Log in instead.',
    loginProfileTimeout: 'Your password was verified, but loading the account timed out. Log in again.',
    loginProfileNetwork: 'Your password was verified, but the network is unavailable. Check your connection and retry.',
    loginProfileServer: 'Your password was verified, but the server could not load the account. Try again.',
    loginSessionFailed: 'Your password was verified, but the session could not be created. Try again.',
    connectionTimeout: 'The server connection timed out. Try again later.',
    networkFailed: 'Network connection failed. Check your connection and retry.',
    credentialsInvalid: 'Incorrect email or password.',
    accountSuspended: 'This account is suspended. Contact support.',
    credentialsFormatInvalid: 'The email or password format is invalid.',
    tooManyAttempts: 'Too many attempts. Try again later.',
    serverUnavailable: 'The server is temporarily unavailable. Try again later.',
    requestFailed: 'Request failed. Try again later.',
    unknownError: 'An unexpected error occurred. Try again later.',
    captchaInvalid: 'The security code is incorrect or expired. Enter a new one.',
    registrationFormatInvalid: 'The email, password or security code format is invalid.',
    registrationFailed: 'Registration failed. Try again later.',
  },
} as const;

export type LanguageMessages = (typeof messages)[AppLanguage];

interface LanguageContextValue {
  language: AppLanguage;
  setLanguage: (language: AppLanguage) => Promise<void>;
  t: LanguageMessages;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<AppLanguage>('zh');

  useEffect(() => {
    let active = true;
    void kvGet(LANGUAGE_KEY).then((stored) => {
      if (active && (stored === 'zh' || stored === 'en')) setLanguageState(stored);
    });
    return () => {
      active = false;
    };
  }, []);

  const value = useMemo<LanguageContextValue>(
    () => ({
      language,
      setLanguage: async (next) => {
        setLanguageState(next);
        await kvSet(LANGUAGE_KEY, next);
      },
      t: messages[language],
    }),
    [language],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage(): LanguageContextValue {
  const value = useContext(LanguageContext);
  if (!value) throw new Error('useLanguage must be used within LanguageProvider');
  return value;
}
